// <auto-generated />
namespace wpfwdb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class moduleTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moduleTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202310161412434_moduleTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
